// ============================================================
// src/scoring/priorityEngine.js
// THE CORE. Deterministic priority scoring — never generated by
// an LLM. Given an incident + live MCP data, produces a 0-100
// score and a fully itemized breakdown. Gemini/Groq only ever
// receive this breakdown afterward to EXPLAIN it in prose —
// they never invent or override a number (see llm/classifier.js
// and agents/coordinaAgent.js for that boundary).
//
// Weights sum to 100. Each factor is normalized to 0-1 before
// weighting, so the final score is always in [0, 100].
// ============================================================
import { mcpClient } from '../mcp/mcpClient.js';

export const WEIGHTS = {
  category: 22,       // medical > shelter > food > logistics > other
  peopleAffected: 20, // scale of impact
  timeWaiting: 18,    // how long the incident has been open
  inventoryGap: 16,   // how short the relevant resource is
  travelTime: 10,     // how far the nearest capable responder is
  shelterOccupancy: 8, // how full shelters are (relevant for shelter-kind)
  volunteerAvailability: 6, // whether responders are actually free
};

const CATEGORY_SEVERITY = {
  medical: 1.0,
  shelter: 0.75,
  food: 0.6,
  logistics: 0.45,
  other: 0.3,
};

function clamp01(n) {
  if (Number.isNaN(n) || n == null) return 0;
  return Math.max(0, Math.min(1, n));
}

function normalizePeopleAffected(n) {
  // 0 people -> 0, 500+ people -> 1, logarithmic so early people
  // matter more than the marginal 400th person of an already-huge incident
  if (!n || n <= 0) return 0;
  return clamp01(Math.log10(n + 1) / Math.log10(501));
}

function normalizeTimeWaiting(createdAt) {
  const hours = (Date.now() - new Date(createdAt).getTime()) / 36e5;
  // 0h -> 0, 24h+ -> 1 (a full day unresolved is treated as maximally urgent on this axis)
  return clamp01(hours / 24);
}

function normalizeInventoryGap(available, needed) {
  if (!needed || needed <= 0) return 0;
  if (available == null) return 0.5; // unknown stock = moderate assumed risk
  const gap = (needed - available) / needed;
  return clamp01(gap);
}

function normalizeTravelTime(minutes) {
  if (minutes == null) return 0.5; // unknown distance = moderate assumed risk
  // 0 min -> 0 urgency-from-distance ... 90+ min -> 1
  return clamp01(minutes / 90);
}

function normalizeShelterOccupancy(occupied, capacity) {
  if (!capacity) return 0;
  return clamp01(occupied / capacity);
}

function normalizeVolunteerAvailability(available) {
  // fewer available volunteers => higher urgency contribution
  if (available == null) return 0.5;
  if (available <= 0) return 1;
  return clamp01(1 / (1 + available / 5));
}

/**
 * Compute the deterministic priority score for an incident.
 * @param {object} incident - row from `incidents` table
 * @param {object} [context] - optional pre-fetched MCP data to avoid refetching in batch scoring
 * @returns {{score: number, breakdown: object}}
 */
export async function scoreIncident(incident, context = {}) {
  const categorySeverity = CATEGORY_SEVERITY[incident.category] ?? CATEGORY_SEVERITY.other;

  const peopleNorm = normalizePeopleAffected(incident.people_affected);
  const timeNorm = normalizeTimeWaiting(incident.created_at);

  // Inventory gap: look up stock for a resource label matching the incident
  // category (best-effort — a real system would map incident->specific SKU).
  let inventoryNorm = 0.5;
  try {
    const shortages = context.shortages ?? (await mcpClient.call('inventory.find_shortages', { thresholdRatio: 0.4 }));
    const relevant = shortages.find((s) => s.organization_id === incident.organization_id) || shortages[0];
    inventoryNorm = relevant
      ? normalizeInventoryGap(relevant.quantity, relevant.capacity ?? relevant.quantity + 1)
      : 0.2;
  } catch { /* MCP unavailable: fall back to moderate assumed risk, never crash scoring */ }

  // Travel time: nearest responder org (any org other than the source)
  let travelNorm = 0.5;
  try {
    const candidates = context.candidateOrgIds ?? [];
    if (candidates.length) {
      const ranked = await mcpClient.call('routing.nearest', {
        targetOrgId: incident.organization_id,
        candidateOrgIds: candidates,
      });
      travelNorm = ranked.length ? normalizeTravelTime(ranked[0].minutes) : 0.5;
    }
  } catch { /* routing unavailable: moderate assumed risk */ }

  // Shelter occupancy: only meaningfully contributes for shelter-category incidents
  let shelterNorm = 0;
  if (incident.category === 'shelter') {
    try {
      const shelters = context.shelters ?? (await mcpClient.call('shelter.get_occupancy', {}));
      if (shelters.length) {
        const avgOccupied = shelters.reduce((s, r) => s + r.quantity, 0);
        const avgCapacity = shelters.reduce((s, r) => s + (r.capacity || 0), 0);
        shelterNorm = normalizeShelterOccupancy(avgOccupied, avgCapacity);
      }
    } catch { /* shelter data unavailable */ }
  }

  // Volunteer availability
  let volunteerNorm = 0.5;
  try {
    const volunteers = context.volunteers ?? (await mcpClient.call('volunteer.get_availability', {}));
    const totalAvailable = volunteers.reduce((s, r) => s + r.quantity, 0);
    volunteerNorm = normalizeVolunteerAvailability(totalAvailable);
  } catch { /* volunteer data unavailable */ }

  const contributions = {
    category: categorySeverity * WEIGHTS.category,
    peopleAffected: peopleNorm * WEIGHTS.peopleAffected,
    timeWaiting: timeNorm * WEIGHTS.timeWaiting,
    inventoryGap: inventoryNorm * WEIGHTS.inventoryGap,
    travelTime: travelNorm * WEIGHTS.travelTime,
    shelterOccupancy: shelterNorm * WEIGHTS.shelterOccupancy,
    volunteerAvailability: volunteerNorm * WEIGHTS.volunteerAvailability,
  };

  const score = Object.values(contributions).reduce((a, b) => a + b, 0);

  return {
    score: Number(score.toFixed(2)),
    breakdown: {
      weights: WEIGHTS,
      normalizedFactors: {
        category: Number(categorySeverity.toFixed(3)),
        peopleAffected: Number(peopleNorm.toFixed(3)),
        timeWaiting: Number(timeNorm.toFixed(3)),
        inventoryGap: Number(inventoryNorm.toFixed(3)),
        travelTime: Number(travelNorm.toFixed(3)),
        shelterOccupancy: Number(shelterNorm.toFixed(3)),
        volunteerAvailability: Number(volunteerNorm.toFixed(3)),
      },
      contributions: Object.fromEntries(
        Object.entries(contributions).map(([k, v]) => [k, Number(v.toFixed(2))])
      ),
      computedAt: new Date().toISOString(),
    },
  };
}

/** Rank a batch of incidents by score, highest first. Never mutates the DB — caller persists. */
export async function rankIncidents(incidents, context = {}) {
  const scored = await Promise.all(
    incidents.map(async (incident) => ({ incident, ...(await scoreIncident(incident, context)) }))
  );
  return scored.sort((a, b) => b.score - a.score);
}
